# Generated by Django 6.1.1 on 2026-09-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenhouses', '0001_initial'),
        ('node', '0002_actuator_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('sensor_device_id', models.CharField(max_length=100)),
                ('field', models.CharField(help_text='e.g. temperature, humidity, soil_moisture', max_length=50)),
                ('condition', models.CharField(choices=[('below', 'Below (<)'), ('above', 'Above (>)'), ('equals', 'Equals (==)')], max_length=20)),
                ('threshold', models.FloatField()),
                ('actuator_device_id', models.CharField(max_length=100)),
                ('command_payload', models.JSONField(default=dict, help_text="JSON payload to dispatch, e.g. {'action': 'on', 'duration_s': 120}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('greenhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='greenhouses.greenhouse')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='node.node')),
            ],
        ),
    ]
