# Generated by Django 6.1.1 on 2026-09-22 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conditions', '0001_initial'),
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='node.node'),
        ),
    ]
