# Generated by Django 6.1.1 on 2026-09-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_initial'),
        ('node', '0002_actuator_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('reading_ts', models.BigIntegerField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='node.node')),
            ],
            options={
                'ordering': ['-reading_ts'],
                'indexes': [models.Index(fields=['device_id', '-reading_ts'], name='conditions__device__ebf2cd_idx')],
            },
        ),
    ]
