# Generated by Django 6.1.1 on 2026-09-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuator_id', models.CharField(max_length=100, unique=True)),
                ('actuator_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='node.node')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100, unique=True)),
                ('sensor_type', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='node.node')),
            ],
        ),
    ]
