# Generated by Django 6.1.1 on 2026-10-02 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouses', '0001_initial'),
        ('node', '0002_actuator_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='claim_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='node',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='hub_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='greenHouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='greenhouses.greenhouse'),
        ),
        migrations.AlterField(
            model_name='node',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(default='gateway', max_length=100),
        ),
    ]
