# Generated by Django 6.1.1 on 2026-10-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_node_claim_code_node_claimed_at_node_hub_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='claim_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='failed_claim_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='hardware_info',
            field=models.CharField(blank=True, default='Raspberry Pi 4B', max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='hub_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='hub_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='one_time_claim_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='one_time_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='software_version',
            field=models.CharField(blank=True, default='0.1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='node',
            name='uptime_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='claim_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='is_claimed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
