# Generated by Django 6.1.1 on 2026-10-07 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_node_claim_locked_until_node_failed_claim_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActuatorCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=3)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('confirmed', 'confirmed'), ('failed', 'failed'), ('expired', 'expired')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='node.actuator')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'delivered'])), fields=('actuator',), name='one_pending_actuator_command')],
            },
        ),
    ]
